# Generated by Django 5.0.7 on 2024-07-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saoapp', '0002_categoria_cliente_producto_delete_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
